# Generated by Django 3.0.4 on 2020-03-22 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_rewiew_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rewiew',
            old_name='commect',
            new_name='comment',
        ),
    ]
